#ifndef CONSTANTS_H
#define CONSTANTS_H

typedef enum Direction {
	DIR_UP,
	DIR_DOWN,
	DIR_LEFT,
	DIR_RIGHT,
} Direction;

typedef enum Constants {

	CONST_SIZE_TILE_WIDTH = 32,
	CONST_SIZE_TILE_HEIGHT = 32,

	CONST_SIZE_GRID_WIDTH = 640,
	CONST_SIZE_GRID_HEIGHT = 480,

	CONST_SIZE_WINDOW_WIDTH = 800,
	CONST_SIZE_WINDOW_HEIGHT = 640,

	CONST_SIZE_TILE_COUNTX = CONST_SIZE_GRID_WIDTH / CONST_SIZE_TILE_WIDTH,
	CONST_SIZE_TILE_COUNTY = CONST_SIZE_GRID_HEIGHT / CONST_SIZE_TILE_HEIGHT,

	CONST_SIZE_LIVE_MARGIN_LEFT = 15,
	CONST_SIZE_LIVE_MARGIN_TOP = 10,

	CONST_SIZE_SCORE_MARGIN_RIGHT = 15,
	CONST_SIZE_SCORE_MARGIN_TOP = 0,

	CONST_MAX_GAMEOBJECTS = 1000,
	CONST_MAX_LIVES = 20,
	CONST_MAX_SCORE_TEXT_LENGTH = 256,

	CONST_INITIAL_UPDATEINTERVAL = 300,
	CONST_INITIAL_LIVES = 3,
	CONST_INITIAL_SCORE = 0,
	CONST_INITIAL_FRUITS = 5,
	CONST_INITIAL_WALLS = 3,
	CONST_INITIAL_SNAKE_DIRECTION = DIR_UP,
	CONST_INITIAL_SNAKE_TILEX = CONST_SIZE_TILE_COUNTX / 2,
	CONST_INITIAL_SNAKE_TILEY = CONST_SIZE_TILE_COUNTY / 2,
	CONST_INITIAL_SNAKE_LENGTH = 1,

	CONST_SCORE_FRUIT_1UP = 500,
	CONST_SCORE_FRUIT_HEART_CONTAINER = 1500,
	CONST_SCORE_FRUIT_STAR = 5400,

} Constants;

typedef enum RendererConstants {

	CONST_COLOR_SCORE_TEXT = 0x00FFFFFF,

	CONST_COLOR_DEBUG_TILE = 0x00A0A0A0,
	CONST_COLOR_DEBUG_SNAKE_HEAD = 0x000000FF,
	CONST_COLOR_DEBUG_SNAKE_BODY = 0x0000FF22,
	CONST_COLOR_DEBUG_SNAKE_TAIL = 0x00004411,
	CONST_COLOR_DEBUG_WALL = 0,
	CONST_COLOR_DEBUG_FRUIT = 0x00FF00000,
	CONST_COLOR_DEBUG_HEART = 0x00FF00000,
} RendererConstants;

#define GET_COLOR(surface, color) (SDL_MapRGB(surface->format, (((color) & 0x00FF0000) >> 16), (((color) & 0x0000FF00) >> 8), (((color) & 0x000000FF))))
#define TO_COLOR(uint) {(((uint) & 0x00FF0000) >> 16), (((uint) & 0x0000FF00) >> 8), ((uint) & 0x000000FF)}

#endif 